-- Houston Live starter schema
-- Run this later in Supabase SQL Editor.

create table venues (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null,
  neighborhood text,
  latitude double precision not null,
  longitude double precision not null,
  has_bar boolean not null default false,
  serves_food boolean not null default false,
  all_ages boolean not null default false,
  created_at timestamptz not null default now()
);

create table bands (
  id bigint generated by default as identity primary key,
  name text not null,
  hometown text,
  bio text,
  instagram_url text,
  bandcamp_url text,
  spotify_url text,
  is_local boolean not null default true,
  created_at timestamptz not null default now()
);

create table genres (
  id bigint generated by default as identity primary key,
  name text unique not null
);

create table band_genres (
  band_id bigint references bands(id) on delete cascade,
  genre_id bigint references genres(id) on delete cascade,
  primary key (band_id, genre_id)
);

create table shows (
  id bigint generated by default as identity primary key,
  title text not null,
  venue_id bigint not null references venues(id),
  starts_at timestamptz not null,
  price numeric(10,2),
  age_restriction text,
  ticket_url text,
  description text,
  status text not null default 'submitted'
    check (status in ('submitted', 'confirmed', 'cancelled')),
  community_submitted boolean not null default true,
  created_at timestamptz not null default now()
);

create table show_bands (
  show_id bigint references shows(id) on delete cascade,
  band_id bigint references bands(id) on delete cascade,
  billing_order integer not null default 1,
  primary key (show_id, band_id)
);

create table submissions (
  id bigint generated by default as identity primary key,
  submitter_name text,
  submitter_email text,
  show_id bigint references shows(id),
  notes text,
  created_at timestamptz not null default now()
);
